basePath: /
definitions:
  db.Gift:
    properties:
      comments:
        type: string
      description:
        type: string
      id:
        description: 'LIFEHACK: use string id like ''gift_ajdsjanjklsnls'''
        type: string
      is_favorite:
        type: boolean
      link:
        type: string
      name:
        description: UserID      string `json:"user_id"`
        type: string
      photo:
        type: string
      price:
        description: 'TODO: use decimal.Decimal instead of int'
        type: integer
    type: object
  db.Seller:
    properties:
      email:
        minLength: 5
        type: string
      name:
        maxLength: 50
        minLength: 5
        type: string
      photo:
        type: string
    required:
    - email
    - name
    type: object
  db.SellerToService:
    properties:
      seller_id:
        type: string
      service_id:
        type: string
    required:
    - seller_id
    - service_id
    type: object
  db.Service:
    properties:
      location:
        minLength: 5
        type: string
      name:
        maxLength: 50
        minLength: 5
        type: string
      photos:
        type: string
      price:
        type: number
    required:
    - location
    - name
    - price
    type: object
  db.ServiceReview:
    properties:
      comment:
        maxLength: 5000
        type: string
      mark:
        type: number
      service_id:
        type: string
      user_id:
        type: string
    required:
    - comment
    - mark
    - service_id
    - user_id
    type: object
  server.ResponseHTTP:
    properties:
      data: {}
      message:
        type: string
      success:
        type: boolean
    type: object
host: localhost:7777
info:
  contact:
    email: fiber@swagger.io
    name: API Support
  description: This is a sample swagger for Fiber
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Wishlist
  version: "1.0"
paths:
  /:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/server.ResponseHTTP'
            - properties:
                data:
                  $ref: '#/definitions/db.Gift'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/server.ResponseHTTP'
      summary: Creates a new gift.
      tags:
      - Gifts
  /sellerToService:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/server.ResponseHTTP'
            - properties:
                data:
                  $ref: '#/definitions/db.SellerToService'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/server.ResponseHTTP'
      summary: Fetches all Seller-Service connections.
      tags:
      - SellerToService
    post:
      consumes:
      - application/json
      parameters:
      - description: Create Selllers-Services
        in: body
        name: SellerToService
        required: true
        schema:
          $ref: '#/definitions/db.SellerToService'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/server.ResponseHTTP'
            - properties:
                data:
                  $ref: '#/definitions/db.SellerToService'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/server.ResponseHTTP'
      summary: Creates a new connection of Seller-Service.
      tags:
      - SellerToService
  /sellerToService/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Service ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/server.ResponseHTTP'
            - properties:
                data:
                  $ref: '#/definitions/db.SellerToService'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/server.ResponseHTTP'
      summary: Deletes a specified Seller-Service connection.
      tags:
      - SellerToService
    get:
      consumes:
      - application/json
      parameters:
      - description: Seller ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/server.ResponseHTTP'
            - properties:
                data:
                  $ref: '#/definitions/db.SellerToService'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/server.ResponseHTTP'
      summary: Fetches all Services that belong to the speicfied Seller.
      tags:
      - SellerToService
  /sellers:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/server.ResponseHTTP'
            - properties:
                data:
                  $ref: '#/definitions/db.Seller'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/server.ResponseHTTP'
      summary: Fetches all sellers.
      tags:
      - Sellers
    post:
      consumes:
      - application/json
      parameters:
      - description: Create Seller
        in: body
        name: Seller
        required: true
        schema:
          $ref: '#/definitions/db.Seller'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/server.ResponseHTTP'
            - properties:
                data:
                  $ref: '#/definitions/db.Seller'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/server.ResponseHTTP'
      summary: Creates a new seller.
      tags:
      - Sellers
  /sellers/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Delete Seller
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/server.ResponseHTTP'
            - properties:
                data:
                  $ref: '#/definitions/db.Seller'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/server.ResponseHTTP'
      summary: Deletes a specified seller.
      tags:
      - Sellers
    get:
      consumes:
      - application/json
      parameters:
      - description: Seller ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/server.ResponseHTTP'
            - properties:
                data:
                  $ref: '#/definitions/db.Seller'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/server.ResponseHTTP'
      summary: Fetches a specific seller.
      tags:
      - Sellers
    patch:
      consumes:
      - application/json
      parameters:
      - description: Update Seller
        in: body
        name: Seller
        required: true
        schema:
          $ref: '#/definitions/db.Seller'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/server.ResponseHTTP'
            - properties:
                data:
                  $ref: '#/definitions/db.Seller'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/server.ResponseHTTP'
      summary: Updates an existing seller.
      tags:
      - Sellers
  /serviceReviews:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/server.ResponseHTTP'
            - properties:
                data:
                  $ref: '#/definitions/db.ServiceReview'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/server.ResponseHTTP'
      summary: Fetches all serviceReviews.
      tags:
      - ServiceReviews
    post:
      consumes:
      - application/json
      parameters:
      - description: Create ServiceReview
        in: body
        name: ServiceReview
        required: true
        schema:
          $ref: '#/definitions/db.ServiceReview'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/server.ResponseHTTP'
            - properties:
                data:
                  $ref: '#/definitions/db.ServiceReview'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/server.ResponseHTTP'
      summary: Creates a new serviceReview.
      tags:
      - ServiceReviews
  /serviceReviews/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Delete ServiceReview
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/server.ResponseHTTP'
            - properties:
                data:
                  $ref: '#/definitions/db.ServiceReview'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/server.ResponseHTTP'
      summary: Deletes a specified serviceReview.
      tags:
      - ServiceReviews
    get:
      consumes:
      - application/json
      parameters:
      - description: ServiceReview ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/server.ResponseHTTP'
            - properties:
                data:
                  $ref: '#/definitions/db.ServiceReview'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/server.ResponseHTTP'
      summary: Fetches a specific serviceReview.
      tags:
      - ServiceReviews
    patch:
      consumes:
      - application/json
      parameters:
      - description: Update ServiceReview
        in: body
        name: ServiceReview
        required: true
        schema:
          $ref: '#/definitions/db.ServiceReview'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/server.ResponseHTTP'
            - properties:
                data:
                  $ref: '#/definitions/db.ServiceReview'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/server.ResponseHTTP'
      summary: Updates an existing serviceReview.
      tags:
      - ServiceReviews
  /serviceReviews/service/{service_id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Service ID
        in: path
        name: service_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/server.ResponseHTTP'
            - properties:
                data:
                  $ref: '#/definitions/db.ServiceReview'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/server.ResponseHTTP'
      summary: Fetches all Service Reviews for a specified Service.
      tags:
      - ServiceReviews
  /services:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/server.ResponseHTTP'
            - properties:
                data:
                  $ref: '#/definitions/db.Service'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/server.ResponseHTTP'
      summary: Fetches all services.
      tags:
      - Services
    post:
      consumes:
      - application/json
      parameters:
      - description: Create Service
        in: body
        name: Service
        required: true
        schema:
          $ref: '#/definitions/db.Service'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/server.ResponseHTTP'
            - properties:
                data:
                  $ref: '#/definitions/db.Service'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/server.ResponseHTTP'
      summary: Creates a new service.
      tags:
      - Services
  /services/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Delete Service
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/server.ResponseHTTP'
            - properties:
                data:
                  $ref: '#/definitions/db.Service'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/server.ResponseHTTP'
      summary: Deletes a specified service.
      tags:
      - Services
    get:
      consumes:
      - application/json
      parameters:
      - description: Service ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/server.ResponseHTTP'
            - properties:
                data:
                  $ref: '#/definitions/db.Service'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/server.ResponseHTTP'
      summary: Fetches a specific service.
      tags:
      - Services
    patch:
      consumes:
      - application/json
      parameters:
      - description: Update Service
        in: body
        name: Service
        required: true
        schema:
          $ref: '#/definitions/db.Service'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/server.ResponseHTTP'
            - properties:
                data:
                  $ref: '#/definitions/db.Service'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/server.ResponseHTTP'
      summary: Updates an existing service.
      tags:
      - Services
swagger: "2.0"
