basePath: /
definitions:
  db.Gift:
    properties:
      description:
        type: string
      id:
        description: 'LIFEHACK: use string id like ''gift_ajdsjanjklsnls'''
        type: string
      link:
        type: string
      name:
        type: string
      photo:
        type: string
      price:
        description: 'TODO: use decimal.Decimal instead of int'
        type: integer
    type: object
  db.User:
    properties:
      birthday:
        type: string
      coins:
        type: integer
      id:
        type: string
      lastname:
        type: string
      login:
        type: string
      name:
        type: string
      password:
        type: string
      role_name:
        type: string
    type: object
  db.UserWishlist:
    properties:
      id:
        type: string
      name:
        type: string
      user_id:
        type: string
    type: object
  db.Wishes:
    properties:
      gift_id:
        type: string
      wishlist_id:
        type: string
    type: object
  server.ResponseHTTP:
    properties:
      data: {}
      message:
        type: string
      success:
        type: boolean
    type: object
host: localhost:7777
info:
  contact:
    email: fiber@swagger.io
    name: API Support
  description: This is a sample swagger for Fiber
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Wishlist
  version: "1.0"
paths:
  /gifts:
    get:
      consumes:
      - application/json
      description: Get all books
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/server.ResponseHTTP'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/db.Gift'
                  type: array
              type: object
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/server.ResponseHTTP'
      summary: Get all books
      tags:
      - Gifts
    post:
      consumes:
      - application/json
      description: get the status of server.
      parameters:
      - description: Create Gift
        in: body
        name: Gift
        required: true
        schema:
          $ref: '#/definitions/db.Gift'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/server.ResponseHTTP'
            - properties:
                data:
                  $ref: '#/definitions/db.Gift'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/server.ResponseHTTP'
      summary: Creates a new gift.
      tags:
      - Gifts
  /gifts/{id}:
    delete:
      consumes:
      - application/json
      description: get the status of server.
      parameters:
      - description: Create Gift
        in: body
        name: Gift
        required: true
        schema:
          $ref: '#/definitions/db.Gift'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/server.ResponseHTTP'
            - properties:
                data:
                  $ref: '#/definitions/db.Gift'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/server.ResponseHTTP'
      summary: Creates a new gift.
      tags:
      - Gifts
    patch:
      consumes:
      - application/json
      description: get the status of server.
      parameters:
      - description: Create Gift
        in: body
        name: Gift
        required: true
        schema:
          $ref: '#/definitions/db.Gift'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/server.ResponseHTTP'
            - properties:
                data:
                  $ref: '#/definitions/db.Gift'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/server.ResponseHTTP'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/server.ResponseHTTP'
      summary: Creates a new gift.
      tags:
      - Gifts
  /login:
    post:
      consumes:
      - application/json
      description: get the status of server.
      parameters:
      - description: Reg user
        in: body
        name: User
        required: true
        schema:
          $ref: '#/definitions/db.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/server.ResponseHTTP'
            - properties:
                data:
                  $ref: '#/definitions/db.User'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/server.ResponseHTTP'
      summary: Creates a new gift.
      tags:
      - auth
  /register:
    post:
      consumes:
      - application/json
      description: get the status of server.
      parameters:
      - description: Reg user
        in: body
        name: User
        required: true
        schema:
          $ref: '#/definitions/db.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/server.ResponseHTTP'
            - properties:
                data:
                  $ref: '#/definitions/db.User'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/server.ResponseHTTP'
      summary: Creates a new gift.
      tags:
      - auth
  /wishes/{id}/{wishlist_id}:
    delete:
      consumes:
      - application/json
      description: get the status of server.
      parameters:
      - description: Add wishes
        in: body
        name: Wishes
        required: true
        schema:
          $ref: '#/definitions/db.Wishes'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/server.ResponseHTTP'
            - properties:
                data:
                  $ref: '#/definitions/db.Wishes'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/server.ResponseHTTP'
      summary: Creates a new gift.
      tags:
      - Wishes
    get:
      consumes:
      - application/json
      description: get the status of server.
      parameters:
      - description: Add wishes
        in: body
        name: Wishes
        required: true
        schema:
          $ref: '#/definitions/db.Wishes'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/server.ResponseHTTP'
            - properties:
                data:
                  $ref: '#/definitions/db.Wishes'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/server.ResponseHTTP'
      summary: Creates a new gift.
      tags:
      - Wishes
  /wishes/{wishlist_id}:
    post:
      consumes:
      - application/json
      description: get the status of server.
      parameters:
      - description: Add wishes
        in: body
        name: Wishes
        required: true
        schema:
          $ref: '#/definitions/db.Wishes'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/server.ResponseHTTP'
            - properties:
                data:
                  $ref: '#/definitions/db.Wishes'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/server.ResponseHTTP'
      summary: Creates a new gift.
      tags:
      - Wishes
  /wishlists:
    get:
      consumes:
      - application/json
      description: get the status of server.
      parameters:
      - description: Create Wishlist
        in: body
        name: UserWishlist
        required: true
        schema:
          $ref: '#/definitions/db.UserWishlist'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/server.ResponseHTTP'
            - properties:
                data:
                  $ref: '#/definitions/db.UserWishlist'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/server.ResponseHTTP'
      summary: Creates a new gift.
      tags:
      - Wishlist
    post:
      consumes:
      - application/json
      description: get the status of server.
      parameters:
      - description: Create Wishlist
        in: body
        name: UserWishlist
        required: true
        schema:
          $ref: '#/definitions/db.UserWishlist'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/server.ResponseHTTP'
            - properties:
                data:
                  $ref: '#/definitions/db.UserWishlist'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/server.ResponseHTTP'
      summary: Creates a new gift.
      tags:
      - Wishlist
    put:
      consumes:
      - application/json
      description: get the status of server.
      parameters:
      - description: Create Wishlist
        in: body
        name: UserWishlist
        required: true
        schema:
          $ref: '#/definitions/db.UserWishlist'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/server.ResponseHTTP'
            - properties:
                data:
                  $ref: '#/definitions/db.UserWishlist'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/server.ResponseHTTP'
      summary: Creates a new gift.
      tags:
      - Wishlist
  /wishlists/{name}:
    get:
      consumes:
      - application/json
      description: get the status of server.
      parameters:
      - description: Create Wishlist
        in: body
        name: UserWishlist
        required: true
        schema:
          $ref: '#/definitions/db.UserWishlist'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/server.ResponseHTTP'
            - properties:
                data:
                  $ref: '#/definitions/db.UserWishlist'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/server.ResponseHTTP'
      summary: Creates a new gift.
      tags:
      - Wishlist
  /wishlists/{wishlist_id}/{gift_id}:
    delete:
      consumes:
      - application/json
      description: get the status of server.
      parameters:
      - description: Delete Wishlist
        in: body
        name: Wishlist
        required: true
        schema:
          $ref: '#/definitions/db.UserWishlist'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/server.ResponseHTTP'
            - properties:
                data:
                  $ref: '#/definitions/db.UserWishlist'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/server.ResponseHTTP'
      summary: Creates a new gift.
      tags:
      - Wishlist
swagger: "2.0"
